[package]
name = "rustawssdk"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
tokio = { version = "1", features = ["full"] }
aws-sdk-dynamodb = "1"
futures = "0.3"
